# Generated by Django 2.0.3 on 2018-03-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название ограждения/балюстрады')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена ограждения/балюстрады')),
            ],
            options={
                'verbose_name': 'Тип ограждения',
                'verbose_name_plural': 'Типы ограждений',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название материала')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена метериала')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Stair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название лестницы')),
                ('min_height', models.PositiveIntegerField(default=600, verbose_name='Минимальная высота лестницы')),
                ('max_height', models.PositiveIntegerField(default=3600, verbose_name='Максимальная высота лестницы')),
                ('step_height', models.PositiveSmallIntegerField(default=5, verbose_name='Шаг высоты лестницы')),
                ('min_marsh', models.PositiveIntegerField(default=550, verbose_name='Минимальная ширина марша')),
                ('max_marsh', models.PositiveIntegerField(default=1300, verbose_name='Максимальная ширина марша')),
                ('step_marsh', models.PositiveSmallIntegerField(default=5, verbose_name='Шаг ширины марша')),
                ('min_width_step', models.PositiveIntegerField(default=100, verbose_name='Минимальная ширина ступени')),
                ('max_width_step', models.PositiveIntegerField(default=350, verbose_name='Максимальная ширина ступени')),
                ('step_width_step', models.PositiveSmallIntegerField(default=5, verbose_name='Шаг ширины ступени')),
                ('min_width_top_step', models.PositiveIntegerField(default=40, verbose_name='Минимальная ширина верхней ступени')),
                ('max_width_top_step', models.PositiveIntegerField(default=300, verbose_name='Максимальная ширина верхней ступени')),
                ('step_width_top_step', models.PositiveSmallIntegerField(default=5, verbose_name='Шаг ширины верхней ступени')),
                ('visible_first_marsh', models.BooleanField(default=True, verbose_name='Ограждение на первом марше')),
                ('visible_invitation_step', models.BooleanField(default=True, verbose_name='Пригласительная ступень')),
                ('visible_riser', models.BooleanField(default=True, verbose_name='Подступенок')),
                ('patina', models.BooleanField(default=True, verbose_name='Патина')),
                ('brush', models.BooleanField(default=True, verbose_name='Браш')),
                ('material_stair', models.ManyToManyField(blank=True, to='API.Material', verbose_name='Доступные материалы')),
            ],
            options={
                'verbose_name': 'Лестница',
                'verbose_name_plural': 'Лестницы',
            },
        ),
        migrations.CreateModel(
            name='Tint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название отделки/тонировки')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена отделки/тонировки')),
            ],
            options={
                'verbose_name': 'Окраска/тонировка',
                'verbose_name_plural': 'Окраска/тонировка',
            },
        ),
        migrations.CreateModel(
            name='TrackSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название пристенного профиля')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена пристенного профиля')),
            ],
            options={
                'verbose_name': 'Пристенный профиль',
                'verbose_name_plural': 'Пристенные профили',
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название поворота')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена поворота')),
            ],
            options={
                'verbose_name': 'Тип поворота',
                'verbose_name_plural': 'Типы поворотов',
            },
        ),
        migrations.AddField(
            model_name='stair',
            name='tint',
            field=models.ManyToManyField(blank=True, to='API.Tint', verbose_name='Варианты отделки'),
        ),
        migrations.AddField(
            model_name='stair',
            name='type_fence',
            field=models.ManyToManyField(blank=True, to='API.Fence', verbose_name='Варианты ограждений'),
        ),
        migrations.AddField(
            model_name='stair',
            name='type_track_support',
            field=models.ManyToManyField(blank=True, to='API.TrackSupport', verbose_name='Варианты пристенного профиля'),
        ),
        migrations.AddField(
            model_name='stair',
            name='type_turn',
            field=models.ManyToManyField(blank=True, to='API.Turn', verbose_name='Варианты поворота'),
        ),
    ]
