# Generated by Django 2.0.3 on 2018-03-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тип ограждения',
                'verbose_name_plural': 'Типы ограждений',
            },
        ),
        migrations.CreateModel(
            name='Stair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_height', models.PositiveIntegerField(default=600, verbose_name='Минимальная высота лестницы')),
                ('max_height', models.PositiveIntegerField(default=3600, verbose_name='Максимальная высота лестницы')),
                ('step_height', models.PositiveSmallIntegerField(default=5)),
                ('min_marsh', models.PositiveIntegerField(default=550)),
                ('max_marsh', models.PositiveIntegerField(default=1300)),
                ('step_marsh', models.PositiveSmallIntegerField(default=5)),
                ('min_width_step', models.PositiveIntegerField(default=100)),
                ('max_width_step', models.PositiveIntegerField(default=350)),
                ('min_width_top_step', models.PositiveIntegerField(default=40)),
                ('max_width_top_step', models.PositiveIntegerField(default=300)),
                ('visible_first_marsh', models.BooleanField(default=True)),
                ('visible_invitation_step', models.BooleanField(default=True)),
                ('visible_riser', models.BooleanField(default=True)),
                ('type_fence', models.ManyToManyField(to='API.Fence')),
            ],
            options={
                'verbose_name': 'Лестница',
                'verbose_name_plural': 'Лестницы',
            },
        ),
        migrations.CreateModel(
            name='TrackSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Пристенный профиль',
                'verbose_name_plural': 'Пристенные профили',
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тип поворота',
                'verbose_name_plural': 'Типы поворотов',
            },
        ),
        migrations.AddField(
            model_name='stair',
            name='type_track_support',
            field=models.ManyToManyField(to='API.TrackSupport'),
        ),
        migrations.AddField(
            model_name='stair',
            name='type_turn',
            field=models.ManyToManyField(to='API.Turn'),
        ),
    ]
