# Generated by Django 2.0.3 on 2018-04-12 07:00

import API.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название ограждения/балюстрады')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена ограждения/балюстрады')),
            ],
            options={
                'verbose_name': 'Тип ограждения',
                'verbose_name_plural': 'Типы ограждений',
            },
        ),
        migrations.CreateModel(
            name='HeightRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('min', models.PositiveIntegerField(default=0)),
                ('slider', API.fields.SliderField()),
                ('max', models.PositiveIntegerField(default=10000)),
                ('step', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название материала')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена метериала')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='MinWidthStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('min', models.PositiveIntegerField(default=0)),
                ('slider', API.fields.SliderField()),
                ('max', models.PositiveIntegerField(default=10000)),
                ('step', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinWidthTopStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('min', models.PositiveIntegerField(default=0)),
                ('slider', API.fields.SliderField()),
                ('max', models.PositiveIntegerField(default=10000)),
                ('step', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название лестницы')),
                ('material_stair', models.ManyToManyField(blank=True, to='API.Material', verbose_name='Доступные материалы')),
            ],
            options={
                'verbose_name': 'Лестница',
                'verbose_name_plural': 'Лестницы',
            },
        ),
        migrations.CreateModel(
            name='Tint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название отделки/тонировки')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена отделки/тонировки')),
            ],
            options={
                'verbose_name': 'Окраска/тонировка',
                'verbose_name_plural': 'Окраска/тонировка',
            },
        ),
        migrations.CreateModel(
            name='TrackSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название пристенного профиля')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена пристенного профиля')),
            ],
            options={
                'verbose_name': 'Пристенный профиль',
                'verbose_name_plural': 'Пристенные профили',
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название поворота')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена поворота')),
            ],
            options={
                'verbose_name': 'Тип поворота',
                'verbose_name_plural': 'Типы поворотов',
            },
        ),
        migrations.CreateModel(
            name='WidthMarsh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('min', models.PositiveIntegerField(default=0)),
                ('slider', API.fields.SliderField()),
                ('max', models.PositiveIntegerField(default=10000)),
                ('step', models.PositiveSmallIntegerField()),
                ('stair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.Stair')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stair',
            name='tint',
            field=models.ManyToManyField(blank=True, to='API.Tint', verbose_name='Варианты отделки'),
        ),
        migrations.AddField(
            model_name='stair',
            name='type_fence',
            field=models.ManyToManyField(blank=True, to='API.Fence', verbose_name='Варианты ограждений'),
        ),
        migrations.AddField(
            model_name='stair',
            name='type_track_support',
            field=models.ManyToManyField(blank=True, to='API.TrackSupport', verbose_name='Варианты пристенного профиля'),
        ),
        migrations.AddField(
            model_name='stair',
            name='type_turn',
            field=models.ManyToManyField(blank=True, to='API.Turn', verbose_name='Варианты поворота'),
        ),
        migrations.AddField(
            model_name='minwidthtopstep',
            name='stair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.Stair'),
        ),
        migrations.AddField(
            model_name='minwidthstep',
            name='stair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.Stair'),
        ),
        migrations.AddField(
            model_name='heightrange',
            name='stair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.Stair'),
        ),
    ]
