# Generated by Django 2.0.3 on 2018-03-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stair',
            name='step_height',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Шаг, с которым будет отображаться высота лестницы'),
        ),
        migrations.AlterField(
            model_name='stair',
            name='type_fence',
            field=models.ManyToManyField(blank=True, null=True, to='API.Fence'),
        ),
        migrations.AlterField(
            model_name='stair',
            name='type_track_support',
            field=models.ManyToManyField(blank=True, null=True, to='API.TrackSupport'),
        ),
        migrations.AlterField(
            model_name='stair',
            name='type_turn',
            field=models.ManyToManyField(blank=True, null=True, to='API.Turn'),
        ),
    ]
