# Generated by Django 2.0.3 on 2018-04-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heightrange',
            options={'verbose_name': 'Высота лестницы', 'verbose_name_plural': 'Высота лестницы'},
        ),
        migrations.AlterModelOptions(
            name='minwidthstep',
            options={'verbose_name': 'Минимальная ширина ступени', 'verbose_name_plural': 'Минимальная ширина ступени'},
        ),
        migrations.AlterModelOptions(
            name='minwidthtopstep',
            options={'verbose_name': 'Минимальная ширина верхней ступени', 'verbose_name_plural': 'Минимальная ширина верхней ступени'},
        ),
        migrations.AlterModelOptions(
            name='widthmarsh',
            options={'verbose_name': 'Ширина марша', 'verbose_name_plural': 'Ширина марша'},
        ),
        migrations.RemoveField(
            model_name='heightrange',
            name='title',
        ),
        migrations.RemoveField(
            model_name='minwidthstep',
            name='title',
        ),
        migrations.RemoveField(
            model_name='minwidthtopstep',
            name='title',
        ),
        migrations.RemoveField(
            model_name='widthmarsh',
            name='title',
        ),
    ]
