# Generated by Django 2.0.3 on 2018-03-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20180328_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stair',
            name='type_fence',
            field=models.ManyToManyField(blank=True, to='API.Fence'),
        ),
        migrations.AlterField(
            model_name='stair',
            name='type_track_support',
            field=models.ManyToManyField(blank=True, to='API.TrackSupport'),
        ),
        migrations.AlterField(
            model_name='stair',
            name='type_turn',
            field=models.ManyToManyField(blank=True, to='API.Turn'),
        ),
    ]
